Repository cnpm/cnpmcore, pull requests merged in 2021-12, with the labels that each got.

#12 feat: using egg-typebox-validate for PackageController
  app/port/controller/PackageController.ts
  config/plugin.ts
  package.json
Labels: enhancement, good first issue

#16 feat: UserRoleManager and developer document
  DEVELOPER.md
  app/core/entity/User.ts
  app/core/service/PackageManagerService.ts
  app/port/UserRoleManager.ts
  app/port/controller/AbstractController.ts
  app/port/controller/PackageController.ts
  app/port/controller/PackageTagController.ts
  app/port/controller/TokenController.ts
  app/port/controller/UserController.ts
  app/port/middleware/AlwaysAuth.ts
  app/port/middleware/ErrorHandler.ts
  app/port/middleware/index.ts
  app/port/type/BaseController.ts
  app/repository/model/User.ts
  config/config.default.ts
  sql/init.sql
  test/port/controller/PackageController.test.ts
  test/port/controller/UserController.test.ts
  test/port/middleware/AlwaysAuth.test.ts
Labels: documentation, enhancement

#17 feat: impl dist-tag API
  DEVELOPER.md
  README.md
  app/common/PackageUtil.ts
  app/core/event/index.ts
  app/core/service/PackageManagerService.ts
  app/core/service/UserService.ts
  app/port/UserRoleManager.ts
  app/port/controller/PackageController.ts
  app/port/controller/PackageTagController.ts
  app/repository/PackageRepository.ts
  config/config.default.ts
  test/TestUtil.ts
  test/port/controller/PackageController.test.ts
  test/port/controller/PackageTagController.test.ts
  test/port/controller/TokenController.test.ts
Labels: enhancement

#19 refactor: upgrade to egg-typebox-validate@2
  DEVELOPER.md
  app/port/controller/AbstractController.ts
  app/port/controller/PackageController.ts
  app/port/controller/PackageTagController.ts
  app/port/typebox.ts
  config/config.default.ts
  config/plugin.ts
  package.json
  test/TestUtil.ts
  test/port/controller/PackageController/downloadVersionTar.test.ts
  test/port/controller/PackageController/saveVersion.test.ts
  test/port/controller/PackageTagController/removeTag.test.ts
  test/port/controller/PackageTagController/saveTag.test.ts
Labels: enhancement

#22 feat: support logout
  app/port/controller/UserController.ts
  test/port/controller/UserController/logout.test.ts
Labels: enhancement

#23 feat: impl sync package
  README.md
  app/common/adapter/NFSAdapter.ts
  app/common/adapter/NPMRegistry.ts
  app/common/enum/Task.ts
  app/core/entity/Task.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/UserService.ts
  app/port/UserRoleManager.ts
  app/port/controller/PackageSyncController.ts
  app/port/typebox.ts
  app/repository/PackageRepository.ts
  app/repository/TaskRepository.ts
  app/repository/model/HistoryTask.ts
  app/repository/model/Package.ts
  app/repository/model/Task.ts
  app/repository/util/ModelConvertor.ts
  app/schedule/SyncPackageWorker.ts
  config/config.default.ts
  package.json
  sql/init.sql
  test/TestUtil.ts
  test/core/service/PackageManagerService/publish.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/core/service/PackageSyncerService/findExecuteTask.test.ts
  test/port/controller/DownloadController/showDownloads.test.ts
  test/port/controller/HomeController/ping.test.ts
  test/port/controller/PackageController/saveVersion.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTaskLog.test.ts
  test/port/controller/PackageTagController/saveTag.test.ts
Labels: enhancement

#24 🤖 TEST: Test on OSS NFS store
  .github/workflows/nodejs.yml
  LICENSE
  app/common/adapter/NFSAdapter.ts
  app/core/entity/Task.ts
  app/core/service/PackageSyncerService.ts
  app/repository/model/HistoryTask.ts
  app/repository/model/Task.ts
  config/config.default.ts
  config/config.unittest.ts
  package.json
  sql/init.sql
  test/TestUtil.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/DownloadController/showDownloads.test.ts
  test/port/controller/PackageController/downloadVersionTar.test.ts
  test/port/controller/PackageController/removeVersion.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTaskLog.test.ts
Labels: enhancement

#26 📦 NEW: allow to disable public registration
  app/port/controller/AbstractController.ts
  app/port/controller/UserController.ts
  config/config.default.ts
  test/port/controller/UserController/loginOrCreateUser.test.ts
Labels: enhancement

#27 👌 IMPROVE: Add deploy scripts on production env
  .gitignore
  app/common/adapter/NFSClientAdapter.ts
  config/config.default.ts
  package.json
Labels: documentation, enhancement

#32 👌 IMPROVE: skip refresh manifests on per version sync
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: documentation

#34 📦 NEW: Support get version from a tag
  app/port/controller/PackageController.ts
  package.json
  test/port/controller/PackageController/showVersion.test.ts
Labels: enhancement

#35 🐛 FIX: Sync package readme maybe is not string type
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#38 🐛 FIX: Support super big dist-tags sync speeds
  app/core/event/index.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/UserService.ts
  app/repository/PackageRepository.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageTagController/removeTag.test.ts
Labels: bug, enhancement

#40 🐛 FIX: Dont sync exists waiting task
  app/core/entity/Task.ts
  app/core/service/PackageSyncerService.ts
  app/repository/TaskRepository.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/core/service/PackageSyncerService/findExecuteTask.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
Labels: bug

#41 📦 NEW: Support concurrent sync package tasks
  app/core/service/PackageSyncerService.ts
  app/schedule/SyncPackageWorker.ts
  config/config.default.ts
Labels: enhancement

#43 🐛 FIX: Handle sync worker error and increae download time
  app/common/adapter/NPMRegistry.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/schedule/CleanTempDir.ts
  app/schedule/SyncPackageWorker.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageController/saveVersion.test.ts
  test/schedule/CleanTempDir.test.ts
  test/schedule/SyncPackageWorker.test.ts
Labels: bug

#49 🐛 FIX: Avoid concurrent sync taks
  app/core/service/PackageSyncerService.ts
  app/repository/TaskRepository.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
Labels: bug

#50 📦 NEW: Support sync all and none mode
  .gitignore
  app/port/controller/AbstractController.ts
  app/port/controller/PackageController.ts
  app/port/controller/PackageSyncController.ts
  app/port/controller/package/DownloadPackageVersionTar.ts
  app/port/controller/package/RemovePackageVersionController.ts
  app/port/controller/package/SavePackageVersionController.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/controller/package/UpdatePackageController.ts
  app/port/middleware/ErrorHandler.ts
  app/schedule/SyncPackageWorker.ts
  config/config.default.ts
  config/config.unittest.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTaskLog.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/controller/package/RemovePackageVersionController.test.ts
  test/port/controller/package/SavePackageVersionController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
  test/port/controller/package/UpdatePackageController.test.ts
  test/schedule/SyncPackageWorker.test.ts
Labels: enhancement

#51 🐛 FIX: dists table should not has path unique key
  sql/init.sql
Labels: bug

#52 📦 NEW: Sync recently updated packages from npm
  app/port/middleware/Tracing.ts
  app/schedule/CheckRecentlyUpdatedPackages.ts
  package.json
  test/.setup.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/middleware/AlwaysAuth.test.ts
  test/port/middleware/Tracing.test.ts
  test/schedule/CheckRecentlyUpdatedPackages.test.ts
  test/schedule/CleanTempDir.test.ts
  test/schedule/SyncPackageWorker.test.ts
Labels: enhancement

#54 👌 IMPROVE: Support cnpmjs.org sync api
  app/port/controller/PackageSyncController.ts
  test/.setup.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
Labels: enhancement

#55 🐛 FIX: Use config registry instead of request href
  app/port/controller/PackageSyncController.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
Labels: bug

#57 🐛 FIX: Ignore npm: prefix on maintainer name
  app/core/entity/Task.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/port/controller/PackageSyncController.ts
  app/repository/model/HistoryTask.ts
  app/repository/model/Task.ts
  sql/init.sql
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/schedule/SyncPackageWorker.test.ts
Labels: bug

#58 📦 NEW: subscribe changes from changes_stream
  app/common/enum/Task.ts
  app/core/entity/Task.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageSyncerService.ts
  app/port/controller/PackageSyncController.ts
  app/repository/TaskRepository.ts
  app/repository/model/Task.ts
  app/schedule/ChangesStreamWorker.ts
  config/config.default.ts
  config/config.unittest.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/schedule/ChangesStreamWorker.test.ts
Labels: enhancement

#59 📦 NEW: Sync removed versions
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#60 👌 IMPROVE: Show user name when user exists
  app/port/controller/UserController.ts
  test/port/controller/UserController/showUser.test.ts
Labels: enhancement

#61 👌 IMPROVE: Use power-assert
  DEVELOPER.md
  test/cli/npm/install.test.ts
  test/common/PackageUtil.test.ts
  test/common/UserUtil.test.ts
  test/core/service/PackageManagerService/publish.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/core/service/PackageSyncerService/findExecuteTask.test.ts
  test/port/controller/DownloadController/showDownloads.test.ts
  test/port/controller/HomeController/ping.test.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTaskLog.test.ts
  test/port/controller/PackageTagController/removeTag.test.ts
  test/port/controller/PackageTagController/saveTag.test.ts
  test/port/controller/PackageTagController/showTags.test.ts
  test/port/controller/TokenController/createToken.test.ts
  test/port/controller/TokenController/listTokens.test.ts
  test/port/controller/TokenController/removeToken.test.ts
  test/port/controller/UserController/loginOrCreateUser.test.ts
  test/port/controller/UserController/logout.test.ts
  test/port/controller/UserController/showUser.test.ts
  test/port/controller/UserController/whoami.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/controller/package/RemovePackageVersionController.test.ts
  test/port/controller/package/SavePackageVersionController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
  test/port/controller/package/UpdatePackageController.test.ts
  test/port/middleware/AlwaysAuth.test.ts
  test/port/middleware/Tracing.test.ts
  test/schedule/ChangesStreamWorker.test.ts
  test/schedule/CheckRecentlyUpdatedPackages.test.ts
  test/schedule/SyncPackageWorker.test.ts
Labels: enhancement

#65 👌 IMPROVE: Forbidden star/unstar command
  app/port/controller/UserController.ts
  app/port/controller/package/SavePackageVersionController.ts
  app/port/middleware/Tracing.ts
  test/port/controller/UserController/starredByUser.test.ts
  test/port/controller/package/SavePackageVersionController.test.ts
Labels: enhancement

#67 🐛 FIX: none syncMode should redirect to source registry
  app/core/service/ChangesStreamService.ts
  app/port/controller/AbstractController.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/middleware/ErrorHandler.ts
  test/cli/npm/install.test.ts
  test/port/controller/PackageTagController/showTags.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
  test/port/middleware/AlwaysAuth.test.ts
Labels: bug

#68 📦 NEW: Support profile command
  app/port/controller/UserController.ts
  test/port/controller/UserController/saveProfile.test.ts
  test/port/controller/UserController/showProfile.test.ts
Labels: enhancement

#69 📦 NEW: Support get total and scope download counts
  app/core/service/PackageManagerService.ts
  app/port/controller/DownloadController.ts
  app/port/controller/HomeController.ts
  app/port/controller/package/DownloadPackageVersionTar.ts
  test/port/controller/DownloadController/showPackageDownloads.test.ts
  test/port/controller/HomeController/ping.test.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
Labels: enhancement

#71 📦 NEW: Show total data on home page request
  app.ts
  app/port/controller/HomeController.ts
  app/repository/PackageRepository.ts
  app/repository/PackageVersionDownloadRepository.ts
  app/schedule/UpdateTotalData.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/schedule/CleanTempDir.test.ts
Labels: enhancement

#72 🧪️ TEST: Add CodeQL action
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#73 📦 NEW: Support changes stream
  README.md
  app.ts
  app/core/entity/Change.ts
  app/core/event/ChangesStream.ts
  app/core/event/index.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageManagerService.ts
  app/port/controller/ChangesStreamController.ts
  app/repository/ChangeRepository.ts
  app/repository/model/Change.ts
  config/config.default.ts
  package.json
  sql/init.sql
  test/port/controller/ChangesStreamController/listChanges.test.ts
Labels: enhancement

#78 👌 IMPROVE: Skip sync remove versions more than 7 days
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/HomeController/showTotal.test.ts
Labels: bug, enhancement

#79 🐛 FIX: Refresh maintainers cache on sync request
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug
