Repository cnpm/cnpmcore, pull requests merged in 2022-02, with the labels that each got.

#136 👌 IMPROVE: Store total data to cache
  .github/workflows/nodejs.yml
  app.ts
  app/core/service/CacheService.ts
  app/port/controller/HomeController.ts
  app/repository/ChangeRepository.ts
  app/schedule/UpdateTotalData.ts
  package.json
  test/port/controller/HomeController/showTotal.test.ts
Labels: enhancement

#137 📦 NEW: Sync node-rc and nightly
  config/binaries.ts
Labels: enhancement

#138 🐛 FIX: Don't create sync task when package missing
  app/port/controller/AbstractController.ts
  app/port/middleware/ErrorHandler.ts
  test/cli/npm/install.test.ts
  test/common/adapter/binary/ApiBinary.test.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/port/controller/PackageTagController/showTags.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: bug, enhancement

#140 🐛 FIX: Save changed date on exists binary item
  app/core/service/BinarySyncerService.ts
Labels: bug

#141 🐛 FIX: use href url instead a text
  app/common/adapter/binary/NodeBinary.ts
  test/common/adapter/binary/NodeBinary.test.ts
Labels: bug

#142 👌 IMPROVE: Only refresh dist-tags to dists
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#143 🐛 FIX: Delete readme from version manifest
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#145 🐛 FIX: Skip zero size file
  app/common/adapter/binary/NodeBinary.ts
  test/common/adapter/binary/NodeBinary.test.ts
Labels: bug

#146 🐛 FIX: Should auto sync removed versions
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#147 👌 IMPROVE: Refresh necessary versions to speed up
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/package/RemovePackageVersionController.test.ts
Labels: enhancement

#148 👌 IMPROVE: Auto clean cache after each sync done
  app/core/service/PackageSyncerService.ts
Labels: enhancement

#149 📦 NEW: Using cnpmcore as changes stream registry
  app/core/service/ChangesStreamService.ts
  app/port/controller/HomeController.ts
  app/schedule/CheckRecentlyUpdatedPackages.ts
  config/config.default.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/schedule/ChangesStreamWorker.test.ts
Labels: enhancement

#150 🐛 FIX: typo fix on dayjs minutes format
  app/core/entity/Task.ts
Labels: bug

#151 🐛 FIX: ignore duplicate key filename on python binary
  app/common/adapter/binary/NodeBinary.ts
  app/port/binary.html
  config/binaries.ts
  test/common/adapter/binary/NodeBinary.test.ts
Labels: bug

#152 👌 IMPROVE: Sync more github releases assets
  app/common/adapter/binary/GithubBinary.ts
  app/common/adapter/binary/PuppeteerBinary.ts
  test/common/adapter/binary/GtihubBinary.test.ts
  test/common/adapter/binary/PuppeteerBinary.test.ts
Labels: enhancement

#153 🐛 FIX: etag match should return vary header too
  app/port/controller/package/ShowPackageController.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: bug

#154 NEW: Sync ffmpeg-static binary
  config/binaries.ts
Labels: enhancement

#155 👌 IMPROVE: Only 3 pages on electron
  app/common/adapter/binary/GithubBinary.ts
  config/binaries.ts
  test/common/adapter/binary/GithubBinary.test.ts
Labels: enhancement

#156 📦 NEW: Sync the last change chromium revision
  app/common/adapter/binary/PuppeteerBinary.ts
  test/common/adapter/binary/PuppeteerBinary.test.ts
Labels: enhancement

#157 🐛 FIX: mozjpeg-bin should use mozjpeg for npm package name
  app/common/adapter/binary/ImageminBinary.ts
  config/binaries.ts
  test/common/adapter/binary/ImageminBinary.test.ts
Labels: bug

#158 👌 IMPROVE: compatible cnpm sync result detect format
  app/port/controller/PackageSyncController.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
Labels: enhancement

#160 fix: fix package typo
  app/common/adapter/binary/ImageminBinary.ts
  app/core/service/PackageManagerService.ts
  app/port/controller/HomeController.ts
  app/repository/PackageRepository.ts
  config/binaries.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/UpdatePackageController.test.ts
Labels: bug

#161 👌 IMPROVE: Only keep one day log
  config/config.default.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/fixtures/downloads.json
  test/schedule/ChangesStreamWorker.test.ts
Labels: enhancement

#163 🐛 FIX: Recheck version data in database
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#165 📦 NEW: Sync looksgood/zeromq.js from github releases
  config/binaries.ts
Labels: enhancement

#166 👌 IMPROVE: Should check version on abbreviated manifests too
  app/core/service/PackageSyncerService.ts
  app/repository/PackageRepository.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#172 📦 NEW: Support block package by admin
  app/core/entity/PackageVersionBlock.ts
  app/core/event/CacheCleaner.ts
  app/core/event/index.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/port/UserRoleManager.ts
  app/port/controller/AbstractController.ts
  app/port/controller/PackageBlockController.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/typebox.ts
  app/repository/PackageVersionBlockRepository.ts
  app/repository/model/PackageVersionBlock.ts
  sql/init.sql
  test/TestUtil.ts
  test/port/controller/PackageBlockController/blockPackage.test.ts
  test/port/controller/PackageBlockController/unblockPackage.test.ts
  test/port/controller/package/SavePackageVersionController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: enhancement

#173 👌 IMPROVE: Move AbstractService to common
  app/common/AbstractService.ts
  app/core/service/BinarySyncerService.ts
  app/core/service/CacheService.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/TaskService.ts
  app/core/service/UserService.ts
Labels: enhancement

#175 👌 IMPROVE: Increase max semi to 128mb
  package.json
Labels: enhancement

#176 👌 IMPROVE: Compatible electron binary sync
  app/common/adapter/binary/ElectronBinary.ts
  app/common/adapter/binary/GithubBinary.ts
  app/core/service/BinarySyncerService.ts
  config/binaries.ts
  test/common/adapter/binary/ElectronBinary.test.ts
Labels: enhancement

#178 📦 NEW: Sync npm binary from github
  config/binaries.ts
Labels: enhancement
