Repository cnpm/cnpmcore, pull requests merged in 2022-08, with the labels that each got.

#277 feat: use sort set to impl queue
  app/common/adapter/QueueAdapter.ts
  app/common/typing.ts
  app/core/service/TaskService.ts
  app/infra/QueueAdapter.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/core/service/PackageSyncerService/findExecuteTask.test.ts
  test/core/service/TaskService/findExecuteTask.test.ts
  test/infra/QueueAdapter.test.ts
Labels: bug, enhancement

#278 🐛 FIX: Handle binary configuration value
  app/common/adapter/binary/NodePreGypBinary.ts
  test/common/adapter/binary/NodePreGypBinary.test.ts
Labels: bug

#292 feat: changesStream adapter & needSync() method
  app/common/adapter/changesStream/AbstractChangesStream.ts
  app/common/adapter/changesStream/CnpmcoreChangesStream.ts
  app/common/adapter/changesStream/CnpmjsorgChangesStream.ts
  app/common/adapter/changesStream/NpmChangesStream.ts
  app/core/entity/Registry.ts
  app/core/entity/Task.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/ScopeManagerService.ts
  app/core/util/ChangesStreamTransform.ts
  app/port/controller/RegistryController.ts
  app/port/controller/ScopeController.ts
  app/repository/ScopeRepository.ts
  app/repository/model/Registry.ts
  test/common/adapter/changesStream/CnpmcoreChangesStream.test.ts
  test/common/adapter/changesStream/CnpmjsorgChangesStream.test.ts
  test/common/adapter/changesStream/NpmChangesStream.test.ts
  test/core/service/ChangesStreamService.test.ts
  test/core/service/RegistryManagerService/index.test.ts
  test/core/util/ChangesStreamTransform.test.ts
  test/repository/TaskRepository.test.ts
Labels: enhancement

#293 feat: sync package from spec regsitry
  app/common/adapter/NPMRegistry.ts
  app/core/entity/Package.ts
  app/core/entity/Task.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/RegistryManagerService.ts
  app/core/service/UserService.ts
  app/port/controller/PackageSyncController.ts
  app/port/controller/RegistryController.ts
  app/port/typebox.ts
  app/repository/RegistryRepository.ts
  app/repository/model/Package.ts
  sql/1.11.0.sql
  test/TestUtil.ts
  test/common/adapter/NpmRegistry.test.ts
  test/core/service/ChangesStreamService.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/core/service/PackageSyncerService/getTaskRegistry.test.ts
  test/core/service/RegistryManagerService/index.test.ts
  test/core/util/ChangesStreamTransform.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/RegistryController/index.test.ts
Labels: enhancement

#300 chore: use AsyncGenerator insteadof Transform stream
  app/common/adapter/changesStream/AbstractChangesStream.ts
  app/common/adapter/changesStream/CnpmcoreChangesStream.ts
  app/common/adapter/changesStream/CnpmjsorgChangesStream.ts
  app/common/adapter/changesStream/NpmChangesStream.ts
  app/core/util/ChangesStreamTransform.ts
  package.json
  test/common/adapter/changesStream/CnpmjsorgChangesStream.test.ts
  test/core/util/ChangesStreamTransform.test.ts
Labels: enhancement

#303 🐛 FIX: Should sync public package when registryName not exists
  app/port/controller/PackageSyncController.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
Labels: bug

#304 fix: changes stream updatedAt
  app/core/service/ChangesStreamService.ts
  test/common/adapter/changesStream/CnpmcoreChangesStream.test.ts
  test/repository/TaskRepository.test.ts
Labels: bug
