Repository cnpm/cnpmcore, pull requests merged in 2022-04, with the labels that each got.

#197 🐛 FIX: Add cache=0 on sync worker request
  app/common/adapter/NPMRegistry.ts
  app/core/service/PackageManagerService.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: bug

#199 fix: versions in manifest may undefined
  app/core/service/BugVersionService.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: bug

#200 fix: show package version should not fix bug version if sync request
  app/core/service/PackageManagerService.ts
  app/port/controller/package/ShowPackageVersionController.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: bug

#202 🐛 FIX: Ignore same version on bug-versions
  app/core/entity/BugVersion.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: bug

#205 👌 IMPROVE: Use task queue on redis instead of MySQL
  app/common/adapter/CacheAdapter.ts
  app/common/adapter/QueueAdapter.ts
  app/core/entity/Task.ts
  app/core/service/BinarySyncerService.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/TaskService.ts
  app/repository/TaskRepository.ts
  app/schedule/TaskTimeoutHandler.ts
  test/.setup.ts
  test/common/adapter/BugVersionStore.test.ts
  test/common/adapter/CacheAdapter.test.ts
  test/core/service/PackageSyncerService/findExecuteTask.test.ts
  test/core/service/TaskService/findExecuteTask.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
  test/port/controller/PackageSyncController/showSyncTask.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/schedule/ChangesStreamWorker.test.ts
  test/schedule/SyncPackageWorker.test.ts
  test/schedule/TaskTimeoutHandler.test.ts
Labels: enhancement

#208 📦 NEW: sqlite3 switch to GitHub releases
  app/common/adapter/binary/Sqlite3Binary.ts
  app/core/service/BinarySyncerService.ts
  config/binaries.ts
  test/common/adapter/binary/Sqlite3Binary.test.ts
Labels: bug, enhancement

#211 👌 IMPROVE: Sync prisma all_commits dir
  config/binaries.ts
  test/common/adapter/binary/BucketBinary.test.ts
Labels: enhancement

#216 🐛 FIX: Auto resync hasInstallScript property
  app/common/PackageUtil.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#214 Update binaries.ts add ali-usb_ctl
  config/binaries.ts
Labels: enhancement
