Repository cnpm/cnpmcore, pull requests merged in 2023-02, with the labels that each got.

#387 refactor: Restrict binaryName types
  app/common/adapter/binary/AbstractBinary.ts
  app/common/adapter/binary/BucketBinary.ts
  app/common/adapter/binary/GithubBinary.ts
  app/common/adapter/binary/ImageminBinary.ts
  app/common/adapter/binary/NodeBinary.ts
  app/common/adapter/binary/NodePreGypBinary.ts
  app/core/service/BinarySyncerService.ts
  app/port/controller/BinarySyncController.ts
  app/port/schedule/CreateSyncBinaryTask.ts
  app/port/typebox.ts
  config/binaries.ts
  test/core/service/BinarySyncerService/createTask.test.ts
Labels: enhancement

#391 fix: allow publish 10mb tarball package by default
  app/port/controller/package/SavePackageVersionController.ts
  config/config.default.ts
  test/port/controller/package/SavePackageVersionController.test.ts
Labels: bug

#393 fix: should init binary adapter before reuse it
  app/common/FileUtil.ts
  app/common/adapter/binary/AbstractBinary.ts
  app/common/adapter/binary/ApiBinary.ts
  app/common/adapter/binary/BucketBinary.ts
  app/common/adapter/binary/CypressBinary.ts
  app/common/adapter/binary/ElectronBinary.ts
  app/common/adapter/binary/GithubBinary.ts
  app/common/adapter/binary/ImageminBinary.ts
  app/common/adapter/binary/NodeBinary.ts
  app/common/adapter/binary/NodePreGypBinary.ts
  app/common/adapter/binary/PlaywrightBinary.ts
  app/common/adapter/binary/PuppeteerBinary.ts
  app/common/adapter/binary/SqlcipherBinary.ts
  app/core/entity/Binary.ts
  app/core/service/BinarySyncerService.ts
  config/binaries.ts
Labels: bug

#399 feat: auto sync package's optionalDependencies
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/fixtures/registry.npmjs.org/resvg-js.json
Labels: enhancement

#398 feat: sync delete mode
  app/common/constants.ts
  app/core/service/PackageSyncerService.ts
  app/infra/NFSClientAdapter.ts
  config/config.default.ts
  test/common/adapter/binary/ImageminBinary.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#405 fix: forbidden non-ascii binary subpath
  app/port/controller/BinarySyncController.ts
  app/port/typebox.ts
  test/port/controller/BinarySyncController/showBinary.test.ts
Labels: bug

#406 fix: distinct processing task
  app/core/service/TaskService.ts
  test/core/service/PackageSyncerService/createTask.test.ts
Labels: bug

#408 fix: changesStream suspend
  app.ts
  app/core/typing.ts
Labels: bug

#413 feat: add integrate doc
  INTEGRATE.md
  README.md
Labels: documentation
