Repository cnpm/cnpmcore, pull requests merged in 2023-03, with the labels that each got.

#414 feat: retry changes task when current work error
  app.ts
  app/core/service/ChangesStreamService.ts
  test/core/service/ChangesStreamService.test.ts
Labels: enhancement

#417 feat: Support for migrating packages into current registry
  DEVELOPER.md
  app/common/PackageUtil.ts
  app/common/constants.ts
  app/core/entity/User.ts
  app/core/service/ChangesStreamService.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/RegistryManagerService.ts
  app/port/UserRoleManager.ts
  app/port/controller/AbstractController.ts
  app/port/controller/PackageTagController.ts
  app/port/controller/UserController.ts
  app/port/controller/package/RemovePackageVersionController.ts
  app/port/controller/package/SavePackageVersionController.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/controller/package/UpdatePackageController.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageTagController/saveTag.test.ts
  test/port/controller/package/RemovePackageVersionController.test.ts
  test/port/controller/package/SavePackageVersionController.test.ts
  test/port/controller/package/UpdatePackageController.test.ts
Labels: enhancement

#418 chore: remove ts-node
  DEVELOPER.md
  package.json
  prepare-database.sh
  test/TestUtil.ts
  test/prepare.ts
  tsconfig.json
Labels: documentation, enhancement

#426 feat: redis weak
  app/port/controller/package/ShowPackageController.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: enhancement

#428 feat: redirect not found can be false when syncMode='none'
  app/port/controller/AbstractController.ts
  config/config.default.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: enhancement

#422 feat: support webauthn
  app/common/CryptoUtil.ts
  app/common/UserUtil.ts
  app/common/enum/User.ts
  app/core/entity/WebauthnCredential.ts
  app/core/service/UserService.ts
  app/port/login.html
  app/port/webauth/WebauthController.ts
  app/repository/UserRepository.ts
  app/repository/model/WebauthnCredential.ts
  config/config.default.ts
  config/plugin.ts
  package.json
  sql/1.13.0.sql
  test/port/controller/package/ShowPackageController.test.ts
  test/port/webauth/webauthController.test.ts
Labels: enhancement

#430 fix: timeout handler not work
  app/core/service/TaskService.ts
  app/repository/util/ModelConvertor.ts
  test/schedule/TaskTimeoutHandler.test.ts
Labels: bug
