Repository cnpm/cnpmcore, pull requests merged in 2023-06, with the labels that each got.

#488 feat: token last used at
  app/core/entity/Token.ts
  app/core/service/TokenService.ts
  app/port/UserRoleManager.ts
  app/port/controller/TokenController.ts
  app/repository/model/Token.ts
  sql/1.16.0.sql
  test/port/controller/TokenController/createToken.test.ts
Labels: sql

#491 feat: add _npmUser
  app/core/service/PackageManagerService.ts
  test/port/controller/package/SavePackageVersionController.test.ts
Labels: bug

#492 fix: hook enable
  app/core/event/ChangesStream.ts
  test/core/event/ChangesStream.test.ts
Labels: bug

#494 feat: whoami granular
  app/core/entity/Token.ts
  app/port/controller/TokenController.ts
  app/port/controller/UserController.ts
  app/repository/UserRepository.ts
  test/port/controller/UserController/whoami.test.ts
Labels: enhancement

#493 feat: source registry manifest
  app/core/service/PackageManagerService.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: enhancement

#495 feat: impl fast semver search
  app/core/entity/PackageVersion.ts
  app/core/entity/PaddingSemVer.ts
  app/core/entity/SqlRange.ts
  app/core/event/BugVersionFixHandler.ts
  app/core/service/BugVersionService.ts
  app/core/service/FixNoPaddingVersionService.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageVersionService.ts
  app/port/controller/PackageVersionFileController.ts
  app/port/controller/admin/PaddingVersionController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/repository/DistRepository.ts
  app/repository/PackageVersionRepository.ts
  app/repository/model/PackageVersion.ts
  package.json
  sql/3.28.0.sql
  test/core/entity/PaddingSemver.test.ts
  test/core/entity/SqlRange.test.ts
  test/core/event/BugVersionFixHandler.test.ts
  test/core/service/PackageVersionService.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: enhancement, sql

#496 feat: infer userPrefix when update maintainers
  app/port/controller/package/UpdatePackageController.ts
  test/TestUtil.ts
  test/port/controller/package/UpdatePackageController.test.ts
Labels: enhancement

#498 fix: ignore fix invalid version
  app/core/entity/PaddingSemVer.ts
  app/core/service/FixNoPaddingVersionService.ts
  sql/3.28.0.sql
Labels: bug

#499 fix: auto fix invalid version to any version
  app/core/entity/PackageVersion.ts
  app/core/entity/PaddingSemVer.ts
  app/core/service/FixNoPaddingVersionService.ts
  test/core/service/BugVersionService/fixPackageBugVersion.test.ts
Labels: bug

#500 refactor: validate spec
  app/port/controller/PackageVersionFileController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/typebox.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
  test/port/controller/PackageVersionFileController/raw.test.ts
  test/port/controller/PackageVersionFileController/sync.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
Labels: enhancement

#501 feat: bulk update maintainers
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/port/controller/package/UpdatePackageController.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#506 fix: sync DOWNLOAD_PATHS code update
  app/common/adapter/binary/PlaywrightBinary.ts
  test/common/adapter/binary/PlaywrightBinary.test.ts
Labels: bug

#487 feat: sync specific versions
  app/core/entity/Task.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/TaskService.ts
  app/port/config.ts
  app/port/controller/PackageSyncController.ts
  app/port/typebox.ts
  app/repository/TaskRepository.ts
  config/config.default.ts
  test/core/service/PackageSyncerService/createTask.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/port/controller/PackageSyncController/createSyncTask.test.ts
Labels: enhancement

#509 feat: support Dockerfile and S3 nfs
  .dockerignore
  Dockerfile
  INTEGRATE.md
  config/config.default.ts
  docs/deploy-in-docker.md
  package.json
Labels: enhancement

#511 feat: use unpkg README.md to update package version readme property
  app/core/service/PackageManagerService.ts
  app/core/service/PackageVersionFileService.ts
  app/core/service/PackageVersionService.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
  test/port/controller/PackageVersionFileController/raw.test.ts
Labels: bug, enhancement

#512 feat: sync package readme
  app/core/event/SyncPackageVersionFile.ts
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/core/service/PackageVersionFileService.ts
  test/port/controller/PackageVersionFileController/raw.test.ts
Labels: enhancement

#514 fix: add block package by packageId and name function
  app/core/service/PackageManagerService.ts
  test/core/service/PackageManagerService/block.test.ts
Labels: enhancement

#522 fix: should redirect when nfs adapter support url
  app/port/controller/AbstractController.ts
  app/port/controller/package/DownloadPackageVersionTar.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
Labels: bug

#527 fix: avoid db query on sync mode all
  app/port/controller/package/DownloadPackageVersionTar.ts
Labels: bug

#526 fix: create sync task by 'GET /:fullname/-/:filenameWithVersion.tgz'
  app/port/controller/AbstractController.ts
  app/port/controller/package/DownloadPackageVersionTar.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
Labels: bug

#533 fix: legacy pkg publish
  app/port/controller/package/SavePackageVersionController.ts
  test/port/controller/package/SavePackageVersionController.test.ts
Labels: bug

#535 fix: only syncUpstream in default registry
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#537 fix: update source registry
  app/core/service/PackageManagerService.ts
  test/port/controller/package/SavePackageVersionController.test.ts
Labels: bug
