Repository cnpm/cnpmcore, pull requests merged in 2023-05, with the labels that each got.

#455 feat: sync chrome-for-testing binary
  app/common/adapter/binary/ChromeForTestingBinary.ts
  app/common/enum/Binary.ts
  config/binaries.ts
  test/common/adapter/binary/ChromeForTestingBinary.test.ts
Labels: enhancement

#459 fix: ignore hidden dir files
  app/core/event/SyncPackageVersionFile.ts
  app/core/service/PackageVersionFileService.ts
  test/fixtures/unpkg.com/bovo-ui-0.0.4-36.tgz
  test/port/controller/PackageVersionFileController/listFiles.test.ts
  test/port/controller/PackageVersionFileController/raw.test.ts
Labels: bug

#460 feat: enable sql logger
  app.ts
  app/core/service/PackageSyncerService.ts
  config/config.default.ts
  package.json
Labels: enhancement

#466 fix: unpublish idempotent
  app/core/service/PackageManagerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: bug

#467 refactor: unpublish logic
  app/core/service/PackageManagerService.ts
Labels: enhancement

#468 feat: easy config
  INTEGRATE.md
  app/common/typing.ts
  app/port/config.ts
  app/port/controller/HomeController.ts
  config/config.default.ts
Labels: documentation, enhancement

#476 fix: refactor config type
  app/common/constants.ts
  app/common/typing.ts
  app/core/service/RegistryManagerService.ts
  app/port/config.ts
  config/config.default.ts
Labels: enhancement

#477 fix: use S3 url to download file
  app/common/adapter/binary/PrismaBinary.ts
  app/core/service/BinarySyncerService.ts
  test/common/adapter/binary/PrismaBinary.test.ts
Labels: bug

#479 fix: unpkg redirect
  app/port/controller/PackageVersionFileController.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
Labels: bug

#485 fix: unpkg support non-npm publish tgz file
  app/core/service/PackageVersionFileService.ts
  test/fixtures/unpkg.com/lodash-es-4.17.7.tgz
  test/port/controller/PackageVersionFileController/raw.test.ts
Labels: bug
