Repository cnpm/cnpmcore, pull requests merged in 2023-01, with the labels that each got.

#372 feat: unpublish pkg when upstream block
  app/core/service/PackageSyncerService.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
Labels: enhancement

#374 fix: export _cnpmcore_publish_time on abbreviated manifests
  app/core/service/PackageManagerService.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: bug

#337 feat: support auto sync when package not found
  app/port/controller/AbstractController.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/middleware/ErrorHandler.ts
  app/port/schedule/ChangesStreamWorker.ts
  app/port/schedule/SyncPackageWorker.ts
  config/config.default.ts
  test/port/controller/package/ShowPackageController.test.ts
Labels: bug, enhancement

#377 fix: not exists binary should return 404
  app/port/controller/BinarySyncController.ts
  test/port/controller/BinarySyncController/showBinary.test.ts
Labels: bug

#378 refactor: re-org binary apdater
  app/common/adapter/binary/AbstractBinary.ts
  app/common/adapter/binary/ApiBinary.ts
  app/common/adapter/binary/BucketBinary.ts
  app/common/adapter/binary/CypressBinary.ts
  app/common/adapter/binary/ElectronBinary.ts
  app/common/adapter/binary/GithubBinary.ts
  app/common/adapter/binary/ImageminBinary.ts
  app/common/adapter/binary/NodeBinary.ts
  app/common/adapter/binary/NodePreGypBinary.ts
  app/common/adapter/binary/NwjsBinary.ts
  app/common/adapter/binary/PlaywrightBinary.ts
  app/common/adapter/binary/PuppeteerBinary.ts
  app/common/adapter/binary/SqlcipherBinary.ts
  app/common/enum/Binary.ts
  app/core/service/BinarySyncerService.ts
  config/binaries.ts
  test/common/adapter/binary/ApiBinary.test.ts
  test/common/adapter/binary/BucketBinary.test.ts
  test/common/adapter/binary/CypressBinary.test.ts
  test/common/adapter/binary/ElectronBinary.test.ts
  test/common/adapter/binary/GithubBinary.test.ts
  test/common/adapter/binary/ImageminBinary.test.ts
  test/common/adapter/binary/NodeBinary.test.ts
  test/common/adapter/binary/NodePreGypBinary.test.ts
  test/common/adapter/binary/NwjsBinary.test.ts
  test/common/adapter/binary/PlaywrightBinary.test.ts
  test/common/adapter/binary/PuppeteerBinary.test.ts
  test/common/adapter/binary/SqlcipherBinary.test.ts
Labels: enhancement

#381 fix: binary path
  app/common/adapter/binary/NodePreGypBinary.ts
  test/common/adapter/binary/NodePreGypBinary.test.ts
Labels: bug

#379 feat: update index json
  app/common/constants.ts
  app/core/service/CacheService.ts
  app/core/service/ChangesStreamService.ts
  app/port/controller/HomeController.ts
  app/port/schedule/UpdateTotalData.ts
  app/repository/PackageRepository.ts
  app/repository/TaskRepository.ts
  test/port/controller/HomeController/showTotal.test.ts
  test/repository/PackageRepository.test.ts
Labels: enhancement

#383 fix: api binary host config
  app/common/adapter/binary/ApiBinary.ts
  test/common/adapter/binary/ApiBinary.test.ts
Labels: bug

#385 fix: config path
  app/common/adapter/binary/ElectronBinary.ts
  app/common/adapter/binary/GithubBinary.ts
  app/common/adapter/binary/ImageminBinary.ts
  app/common/adapter/binary/NodeBinary.ts
  app/common/adapter/binary/NodePreGypBinary.ts
  app/common/adapter/binary/NwjsBinary.ts
Labels: bug
