Repository cnpm/cnpmcore, pull requests merged in 2023-09, with the labels that each got.

#513 feat: support npm search command like npmio
  app/common/PackageUtil.ts
  app/common/typing.ts
  app/core/event/SyncESPackage.ts
  app/core/service/PackageSearchService.ts
  app/core/service/PackageSyncerService.ts
  app/infra/SearchAdapter.ts
  app/port/config.ts
  app/port/controller/package/SearchPackageController.ts
  app/port/typebox.ts
  app/repository/PackageRepository.ts
  app/repository/SearchRepository.ts
  config/config.default.ts
  config/config.unittest.ts
  config/plugin.ts
  docs/elasticsearch-setup.md
  package.json
  test/common/PackageUtil.test.ts
  test/port/controller/package/SearchPackageController.test.ts
  test/repository/SearchRepository.test.ts
Labels: enhancement

#580 fix: use env.CNPMCORE_CONFIG_ENABLE_ES to enable
  config/config.default.ts
  docs/elasticsearch-setup.md
Labels: enhancement

#581 fix: author info
  app/core/service/PackageSearchService.ts
  app/repository/SearchRepository.ts
  docs/elasticsearch-setup.md
Labels: bug, documentation

#582 fix: author display in cli
  app/core/service/PackageSearchService.ts
  app/repository/PackageRepository.ts
  app/repository/SearchRepository.ts
  docs/elasticsearch-setup.md
Labels: bug, documentation

#587 fix: fix the issue where the license may be an object
  app/core/service/PackageSearchService.ts
  app/repository/PackageRepository.ts
Labels: bug

#592 feat: sync all crhome for test binaries
  .github/workflows/codeql-analysis.yml
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  app/common/adapter/binary/ChromeForTestingBinary.ts
  package.json
  test/common/adapter/binary/ChromeForTestingBinary.test.ts
  test/fixtures/chrome-for-testing/known-good-versions-with-downloads.json
  tsconfig.json
Labels: enhancement
