Repository cnpm/cnpmcore, pull requests merged in 2024-05, with the labels that each got.

#676 feat: mirror edgewebdriver
  app/common/adapter/binary/EdgedriverBinary.ts
  app/common/enum/Binary.ts
  config/binaries.ts
  test/common/adapter/binary/EdgedriverBinary.test.ts
  test/fixtures/edgeupdates.json
Labels: enhancement

#677 fix: only set err.status on statusCode >= 200
  app/port/middleware/ErrorHandler.ts
Labels: bug

#681 feat: update playwright config
  app/common/adapter/binary/PlaywrightBinary.ts
  test/common/adapter/binary/PlaywrightBinary.test.ts
Labels: enhancement

#666 chore: add sync-setup
  docs/sync-setup.md
Labels: documentation

#675 feat: support unpkg alias path access entry file #674
  app/port/controller/PackageVersionFileController.ts
  test/fixtures/@cnpm/cnpm-test-find-entry-1.0.0.tgz
  test/port/controller/PackageVersionFileController/listFiles.test.ts
Labels: enhancement

#683 fix: remove CVE-2023-46809 revert config
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  app/common/CryptoUtil.ts
  package.json
  test/common/CryptoUtil.test.ts
  test/port/webauth/webauthController.test.ts
Labels: enhancement

#686 feat: add unpkg-white-list to detect sync unpkg files or not
  app.ts
  app/core/event/SyncPackageVersionFile.ts
  app/core/service/PackageVersionFileService.ts
  app/port/config.ts
  app/port/controller/PackageVersionFileController.ts
  app/port/controller/package/SavePackageVersionController.ts
  config/config.default.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
Labels: enhancement

#687 fix: files meta only return currrent files and sub directory
  app/port/controller/PackageVersionFileController.ts
  app/repository/PackageVersionFileRepository.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
  test/port/controller/PackageVersionFileController/raw.test.ts
Labels: bug, enhancement

#690 feat: mirror homebrew-macos-cross-toolchains
  config/binaries.ts
Labels: enhancement

#691 feat: sync missing acceptDependencies on abbreviated format
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/repository/PackageRepository.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/fixtures/registry.npmjs.org/accept-dependencies-module-cnpmsync.json
Labels: enhancement

#692 fix: rc version should match `*` version
  app/core/service/PackageVersionFileService.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
Labels: bug

#694 fix: support + wildcast
  app/core/service/PackageVersionFileService.ts
  test/port/controller/PackageVersionFileController/listFiles.test.ts
Labels: bug
