Repository cnpm/cnpmcore, pull requests merged in 2024-10, with the labels that each got.

#571 feat: proxy mode [sql changed]
  app/common/adapter/NPMRegistry.ts
  app/common/constants.ts
  app/common/enum/Task.ts
  app/core/entity/ProxyCache.ts
  app/core/entity/Task.ts
  app/core/service/ProxyCacheService.ts
  app/port/controller/ProxyCacheController.ts
  app/port/controller/package/DownloadPackageVersionTar.ts
  app/port/controller/package/ShowPackageController.ts
  app/port/controller/package/ShowPackageVersionController.ts
  app/port/schedule/CheckProxyCacheUpdateWorker.ts
  app/port/schedule/CheckRecentlyUpdatedPackages.ts
  app/port/schedule/SyncProxyCacheWorker.ts
  app/repository/ProxyCacheRepository.ts
  app/repository/model/ProxyCache.ts
  package.json
  sql/3.67.0.sql
  test/core/service/ProxyCacheService.test.ts
  test/fixtures/registry.npmjs.org/abbreviated_foobar.json
  test/fixtures/registry.npmjs.org/foobar/1.0.0/abbreviated.json
  test/fixtures/registry.npmjs.org/foobar/1.0.0/package.json
  test/port/controller/ProxyCacheController/index.test.ts
  test/port/controller/package/DownloadPackageVersionTarController.test.ts
  test/port/controller/package/ShowPackageController.test.ts
  test/port/controller/package/ShowPackageVersionController.test.ts
  test/repository/ProxyCachePepository.test.ts
  test/schedule/CheckProxyCacheUpdateWorker.test.ts
  test/schedule/SyncProxyCacheWorker.test.ts
Labels: enhancement, sql

#715 fix: change skia-canvas to github release
  config/binaries.ts
  test/common/adapter/binary/GithubBinary.test.ts
  test/common/adapter/binary/NodePreGypBinary.test.ts
  test/fixtures/skia-canvas-releases.json
Labels: bug

#717 feat: add protobuf
  config/binaries.ts
  test/common/adapter/binary/GithubBinary.test.ts
  test/fixtures/protobuf-releases.json
Labels: enhancement

#720 feat: strict validate deps
  app/core/service/PackageManagerService.ts
  app/core/service/PackageSyncerService.ts
  app/port/config.ts
  config/config.default.ts
  test/core/service/PackageManagerService/publish.test.ts
  test/core/service/PackageSyncerService/executeTask.test.ts
  test/fixtures/registry.npmjs.org/invalid-deps.json
Labels: enhancement
