Repository cnpm/cnpmcore, pull requests merged in 2025-04, with the labels that each got.

#786 feat(sql): add gmt_create for binaries index idx_category_parent_gmt_create
  app/common/adapter/binary/PuppeteerBinary.ts
  sql/ddl_mysql.sql
  sql/ddl_postgresql.sql
  sql/mysql/4.2.0.sql
  sql/postgresql/4.2.0.sql
Labels: sql

#787 feat: mirror astral-sh/python-build-standalone
  config/binaries.ts
Labels: enhancement

#790 feat: add onnxruntime binary mirror
  config/binaries.ts
Labels: enhancement

#792 feat: use npm new replication api
  app/common/adapter/changesStream/NpmChangesStream.ts
  test/common/adapter/changesStream/NpmChangesStream.test.ts
  test/core/service/ChangesStreamService.test.ts
Labels: enhancement

#793 chore: custom registry
  docs/sync-setup.md
Labels: documentation

#795 fix: init release
  app/common/adapter/binary/GithubBinary.ts
Labels: bug

#797 refactor: doc_count & doc_version_count perf
  app/common/enum/Total.ts
  app/core/event/TotalHandler.ts
  app/core/event/index.ts
  app/core/service/PackageManagerService.ts
  app/port/schedule/UpdateTotalData.ts
  app/repository/PackageRepository.ts
  app/repository/TotalRepository.ts
  app/repository/model/Total.ts
  sql/ddl_mysql.sql
  sql/ddl_postgresql.sql
  sql/mysql/4.3.0.sql
  sql/postgresql/4.3.0.sql
  test/port/controller/HomeController/showTotal.test.ts
  test/repository/PackageRepository.test.ts
  test/repository/TotalRepository.test.ts
Labels: enhancement
